import React from "react";

export const Data8_5 = () => {
    return (
        <div>
            
            <strong>
            Partitions, Forks
            </strong>

            <p>
            Forks can arise at PoH tick counts that correspond to a vote. The next leader may not have observed the last vote slot and may start their slot with generated virtual PoH entries. These empty ticks are generated by all nodes in the cluster at a cluster-configured rate for hashes/per/tick Z
            </p>
            <br></br>
            <p>
            There are only two possible versions of the PoH during a voting slot: PoH with T ticks and entries generated by the current leader, or PoH with just ticks. The "just ticks" version of the PoH can be thought of as a virtual ledger, one that all nodes in the cluster can derive from the last tick in the previous slot.
            </p>
            <br></br>
            <p>
            Validators can ignore forks at other points (e.g. from the wrong leader), or slash the leader responsible for the fork.
            </p>
            <br></br>
            <p>
            Validators vote based on a greedy choice to maximize their reward described in Tower BFT.
            </p>
            
            
            
        </div>

    );
}